# Generated by Django 3.1.5 on 2021-08-03 18:22

from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyTerms',
            fields=[
                ('policy_no', models.AutoField(db_column='POLICY_NO', primary_key=True, serialize=False)),
                ('policy_title', models.CharField(db_column='POLICY_TITLE', max_length=500)),
                ('policy_content', django_summernote.fields.SummernoteTextField(db_column='POLICY_CONTENT', max_length=1000000)),
                ('policy_updated', models.DateTimeField(auto_now=True, db_column='POLICY_UPDATED')),
            ],
            options={
                'db_table': 'POLICY_TERMS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyType',
            fields=[
                ('type_no', models.AutoField(db_column='TYPE_NO', primary_key=True, serialize=False)),
                ('type_name', models.CharField(db_column='TYPE_NAME', max_length=100)),
            ],
            options={
                'db_table': 'POLICY_TYPE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LectEnrollmentStatus',
            fields=[
                ('status', models.IntegerField(db_column='STATUS', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=10)),
            ],
        ),
    ]
