# Generated by Django 3.1.5 on 2021-02-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEmailaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254, unique=True)),
                ('verified', models.IntegerField()),
                ('primary', models.IntegerField()),
            ],
            options={
                'db_table': 'account_emailaddress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountEmailconfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'account_emailconfirmation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'django_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestForm',
            fields=[
                ('quest_no', models.AutoField(db_column='QUEST_NO', primary_key=True, serialize=False)),
                ('quest_name', models.CharField(db_column='QUEST_NAME', max_length=500)),
            ],
            options={
                'db_table': 'QUEST_FORM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('uid', models.CharField(max_length=191)),
                ('last_login', models.DateTimeField()),
                ('date_joined', models.DateTimeField()),
                ('extra_data', models.TextField()),
            ],
            options={
                'db_table': 'socialaccount_socialaccount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('client_id', models.CharField(max_length=191)),
                ('secret', models.CharField(max_length=191)),
                ('key', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'socialaccount_socialapp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialappSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'socialaccount_socialapp_sites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialtoken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('token_secret', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'socialaccount_socialtoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLoginBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'social_login_blog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_email', models.CharField(db_column='USER_EMAIL', max_length=100)),
                ('user_token', models.CharField(db_column='USER_TOKEN', max_length=1000)),
                ('user_stu', models.IntegerField(db_column='USER_STU', primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='USER_NAME', max_length=50)),
                ('user_major', models.CharField(db_column='USER_MAJOR', max_length=50)),
                ('user_pic', models.CharField(db_column='USER_PIC', max_length=1000)),
                ('user_auth', models.IntegerField(db_column='USER_AUTH')),
                ('user_role', models.IntegerField(db_column='USER_ROLE')),
                ('user_joined', models.DateTimeField(blank=True, db_column='USER_JOINED', null=True)),
                ('user_grade', models.IntegerField(db_column='USER_GRADE')),
                ('user_gen', models.IntegerField(db_column='USER_GEN')),
            ],
            options={
                'db_table': 'USER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('auth_no', models.AutoField(db_column='AUTH_NO', primary_key=True, serialize=False)),
                ('auth_name', models.CharField(db_column='AUTH_NAME', max_length=50)),
            ],
            options={
                'db_table': 'USER_AUTH',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_no', models.AutoField(db_column='ROLE_NO', primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, db_column='ROLE_NAME', max_length=50, null=True)),
            ],
            options={
                'db_table': 'USER_ROLE',
                'managed': False,
            },
        ),
    ]
