# Generated by Django 3.1.5 on 2021-04-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectDay',
            fields=[
                ('day_no', models.AutoField(db_column='DAY_NO', primary_key=True, serialize=False)),
                ('day_name', models.CharField(db_column='DAY_NAME', max_length=2)),
            ],
            options={
                'db_table': 'LECT_DAY',
                'managed': False,
            },
        ),
    ]
