# Generated by Django 3.1.5 on 2021-08-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_lectenrollmentstatus_policyterms_policytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentType',
            fields=[
                ('comment_type_no', models.AutoField(db_column='TYPE_NO', primary_key=True, serialize=False)),
                ('comment_type_name', models.CharField(db_column='TYPE_NAME', max_length=20)),
            ],
            options={
                'db_table': 'COMMENT_TYPE',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ContestComment',
        ),
        migrations.DeleteModel(
            name='LectBoardComment',
        ),
        migrations.DeleteModel(
            name='UserDeleteComment',
        ),
    ]
