# Generated by Django 3.1.5 on 2021-02-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0003_answer_bank_bankfile_board_boardfile_boardtype_comment_contestboard_contestfile_lect_lectboard_lectb'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeleteFile',
            fields=[
                ('user_delete_id', models.AutoField(db_column='USER_DELETE_ID', primary_key=True, serialize=False)),
                ('user_delete_file_path', models.CharField(db_column='USER_DELETE_FILE_PATH', max_length=1000)),
            ],
            options={
                'db_table': 'USER_DELETE_FILE',
                'managed': False,
            },
        ),
    ]
